set working-directory := ".."

# Build docker image with target ci
build:
    docker build --target ci -t ttungbmt/superset:6.1.0 .

# Start the Superset application
up:
    docker compose -f docker-compose-image-tag.yml up -d

# Stop the Superset application and remove containers
down:
    docker compose -f docker-compose-image-tag.yml down
