version: "3"

vars:
  DOCKER_COMPOSE_FILE: "docker-compose-image-tag.yml"
  IMAGE_TAG: "ttungbmt/superset:6.1.0"

# Define common settings using YAML anchor
.setup: &setup
  dir: ..

tasks:
  build:
    desc: Build docker image with target ci
    <<: *setup
    cmds:
      - docker build --target lean -t {{.IMAGE_TAG}} .

  up:
    desc: Start the Superset application
    <<: *setup
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} up -d

  down:
    desc: Stop the Superset application and remove containers
    <<: *setup
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down

  push:
    desc: Push docker image to registry
    <<: *setup
    cmds:
      - docker push {{.IMAGE_TAG}}

  build-push:
    desc: Build and push docker image
    cmds:
      - task: build
      - task: push

  reset:
    desc: Stop the Superset application and remove containers along with volumes
    <<: *setup
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE_FILE}} down -v
